# Generated by Django 4.2.9 on 2026-05-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_metrics_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentdecisiontrace',
            new_name='tickets_age_ticket__067a7c_idx',
            old_name='tickets_agt_ticket_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstatusevent',
            new_name='tickets_ord_shopify_6f3427_idx',
            old_name='tickets_ord_shopify_8f3c9d_idx',
        ),
    ]
